            - name: Cache
  uses: actions/cache@v3.4.2
  with:
    # A list of files, directories, and wildcard patterns to cache and restore
    path: 
    # An explicit key for restoring and saving the cache
    key: 
    # An ordered list of keys to use for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
    restore-keys: # optional
    # The chunk size used to split up large files during upload, in bytes
    upload-chunk-size: # optional
    # An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms
    enableCrossOsArchive: # optional, default is false
    # Fail the workflow if cache entry is not found
    fail-on-cache-miss: # optional, default is false
    # Check if a cache entry exists for the given input(s) (key, restore-keys) without downloading the cache
    lookup-only: # optional, default is false
          version: 0.0
os: linux
files:
  - source: .
    destination: /opt/app
hooks:
  ApplicationStop:
    - location: bin/deployment/stop
      timeout: 300
  AfterInstall:
    - location: bin/deployment/build
  ApplicationStart:
    - location: bin/deployment/migrate
      runas: ec2-user
      timeout: 300
    - location: bin/deployment/start
      timeout: 3600
  ValidateService:
    - location: bin/deployment/health_check
      timeout: 3600
